//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViAppleGrab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.100")]
        public string IP_ADDRESS {
            get {
                return ((string)(this["IP_ADDRESS"]));
            }
            set {
                this["IP_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MAX_CONTROLLERS {
            get {
                return ((int)(this["MAX_CONTROLLERS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BASE_ALIVE_TIME {
            get {
                return ((int)(this["BASE_ALIVE_TIME"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MAX_LEVELS {
            get {
                return ((int)(this["MAX_LEVELS"]));
            }
            set {
                this["MAX_LEVELS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_KEYBOARD_ONLY {
            get {
                return ((bool)(this["USE_KEYBOARD_ONLY"]));
            }
            set {
                this["USE_KEYBOARD_ONLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620")]
        public int MAX_X {
            get {
                return ((int)(this["MAX_X"]));
            }
            set {
                this["MAX_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MIN_X {
            get {
                return ((int)(this["MIN_X"]));
            }
            set {
                this["MIN_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460")]
        public int MAX_Y {
            get {
                return ((int)(this["MAX_Y"]));
            }
            set {
                this["MAX_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MIN_Y {
            get {
                return ((int)(this["MIN_Y"]));
            }
            set {
                this["MIN_Y"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7899")]
        public int PORT {
            get {
                return ((int)(this["PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TIME_DECREASE_PER_LEVEL {
            get {
                return ((int)(this["TIME_DECREASE_PER_LEVEL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int BASE_LEVEL_TIME {
            get {
                return ((int)(this["BASE_LEVEL_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ALIVE_TIME_DECREASE_PER_LEVEL {
            get {
                return ((int)(this["ALIVE_TIME_DECREASE_PER_LEVEL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int KEYBOARD_CONTROLLER_INCREMENT {
            get {
                return ((int)(this["KEYBOARD_CONTROLLER_INCREMENT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int UPDATE_INTERVAL {
            get {
                return ((int)(this["UPDATE_INTERVAL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_CALIBRATED {
            get {
                return ((bool)(this["IS_CALIBRATED"]));
            }
            set {
                this["IS_CALIBRATED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAL_X_MIN {
            get {
                return ((int)(this["CAL_X_MIN"]));
            }
            set {
                this["CAL_X_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int CAL_X_MAX {
            get {
                return ((int)(this["CAL_X_MAX"]));
            }
            set {
                this["CAL_X_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAL_Y_MIN {
            get {
                return ((int)(this["CAL_Y_MIN"]));
            }
            set {
                this["CAL_Y_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int CAL_Y_MAX {
            get {
                return ((int)(this["CAL_Y_MAX"]));
            }
            set {
                this["CAL_Y_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int CAL_X_RANGE {
            get {
                return ((int)(this["CAL_X_RANGE"]));
            }
            set {
                this["CAL_X_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int CAL_Y_RANGE {
            get {
                return ((int)(this["CAL_Y_RANGE"]));
            }
            set {
                this["CAL_Y_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int SCREEN_WIDTH {
            get {
                return ((int)(this["SCREEN_WIDTH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int SCREEN_HEIGHT {
            get {
                return ((int)(this["SCREEN_HEIGHT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public int HAND_SPRITE_SIDE_LENGTH {
            get {
                return ((int)(this["HAND_SPRITE_SIDE_LENGTH"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CONTROL_TYPE {
            get {
                return ((int)(this["CONTROL_TYPE"]));
            }
            set {
                this["CONTROL_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GAME_TYPE {
            get {
                return ((int)(this["GAME_TYPE"]));
            }
            set {
                this["GAME_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public int TARGET_SPRITE_SIDE_LENGTH {
            get {
                return ((int)(this["TARGET_SPRITE_SIDE_LENGTH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PREDEFINED_TARGETS {
            get {
                return ((bool)(this["PREDEFINED_TARGETS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int TIME_TO_COLLECT_TARGET {
            get {
                return ((int)(this["TIME_TO_COLLECT_TARGET"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAL_LEFT_SHOULDER_X {
            get {
                return ((int)(this["CAL_LEFT_SHOULDER_X"]));
            }
            set {
                this["CAL_LEFT_SHOULDER_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAL_LEFT_SHOULDER_Y {
            get {
                return ((int)(this["CAL_LEFT_SHOULDER_Y"]));
            }
            set {
                this["CAL_LEFT_SHOULDER_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAL_RIGHT_SHOULDER_X {
            get {
                return ((int)(this["CAL_RIGHT_SHOULDER_X"]));
            }
            set {
                this["CAL_RIGHT_SHOULDER_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAL_RIGHT_SHOULDER_Y {
            get {
                return ((int)(this["CAL_RIGHT_SHOULDER_Y"]));
            }
            set {
                this["CAL_RIGHT_SHOULDER_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QUICK_CALIBRATION {
            get {
                return ((bool)(this["QUICK_CALIBRATION"]));
            }
            set {
                this["QUICK_CALIBRATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SCORE_PER_APPLE_INCREASE {
            get {
                return ((int)(this["SCORE_PER_APPLE_INCREASE"]));
            }
            set {
                this["SCORE_PER_APPLE_INCREASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int INITIAL_SCORE_PER_APPLE {
            get {
                return ((int)(this["INITIAL_SCORE_PER_APPLE"]));
            }
            set {
                this["INITIAL_SCORE_PER_APPLE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IN_TESTING_MODE {
            get {
                return ((bool)(this["IN_TESTING_MODE"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int BUZZ_DURATION {
            get {
                return ((int)(this["BUZZ_DURATION"]));
            }
            set {
                this["BUZZ_DURATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RIGHT_GIVES_Y_FEEDBACK {
            get {
                return ((bool)(this["RIGHT_GIVES_Y_FEEDBACK"]));
            }
            set {
                this["RIGHT_GIVES_Y_FEEDBACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SHOW_CAMERA {
            get {
                return ((bool)(this["SHOW_CAMERA"]));
            }
            set {
                this["SHOW_CAMERA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TIMED_GAME {
            get {
                return ((bool)(this["TIMED_GAME"]));
            }
            set {
                this["TIMED_GAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TARGETS_PER_LEVEL {
            get {
                return ((int)(this["TARGETS_PER_LEVEL"]));
            }
            set {
                this["TARGETS_PER_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Targets_Together.txt")]
        public string TOGETHER_FILE {
            get {
                return ((string)(this["TOGETHER_FILE"]));
            }
            set {
                this["TOGETHER_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Targets_Alternating.txt")]
        public string ALTERNATING_FILE {
            get {
                return ((string)(this["ALTERNATING_FILE"]));
            }
            set {
                this["ALTERNATING_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HIDE_OUTPUT {
            get {
                return ((bool)(this["HIDE_OUTPUT"]));
            }
            set {
                this["HIDE_OUTPUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SIMULTANEOUS_TARGETS {
            get {
                return ((bool)(this["SIMULTANEOUS_TARGETS"]));
            }
            set {
                this["SIMULTANEOUS_TARGETS"] = value;
            }
        }
    }
}
